spring:
    redis:
        host: local.redis.com
        port: 6379
        password:
        timeout: 10s
        lettuce:
            pool:
                min-idle: 0
                max-idle: 8
                max-active: 8
                max-wait: -1ms
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://local.mysql.com:3306/xm_exam?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8
        username: root
        password: 123456
        hikari:
            minimum-idle: 5
            maximum-pool-size: 20
            connection-test-query: SELECT 1
    mvc:
        servlet:
            load-on-startup: 1
access_token:
    store-jwt: false
    jwt-signing-key: jia@gou=$==+_+%0%:)(:)
    add-userinfo: false

ribbon:
    eager-load:
        enabled: true
        clients: user-center
    ReadTimeout: 10000
    ConnectTimeout: 10000
hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 60000
